# Generated by Django 5.2.4 on 2025-08-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('0', 'Complete')], default=1, max_length=15),
        ),
    ]
