# Generated by Django 5.2.4 on 2025-08-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_transaction_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('0', 'Complete'), ('2', 'Failed'), ('3', 'Cancelled'), ('4', 'Timeout')], default=1, max_length=15),
        ),
    ]
